# Generated by Django 4.2.8 on 2024-01-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='isactive',
            field=models.BooleanField(default=False, verbose_name='Öne Çıkanlarda Göster'),
        ),
    ]
