# Generated by Django 4.2.8 on 2024-01-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_news_isactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='isactive',
            new_name='left',
        ),
        migrations.AddField(
            model_name='news',
            name='slider',
            field=models.BooleanField(default=False, verbose_name='Sliderda Göster'),
        ),
    ]
