# Generated by Django 4.2.8 on 2024-01-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_rename_isactive_news_left_news_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='Ad-Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('title', models.TextField(verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Messaj')),
                ('date_now', models.DateTimeField(auto_now_add=True, verbose_name='Tarih-Saat')),
            ],
        ),
    ]
