# Generated by Django 4.2.8 on 2024-01-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0006_alter_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_now',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Tarih Saat'),
        ),
    ]
