# Generated by Django 4.2.8 on 2024-01-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0010_news_category_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Haber Resim'),
        ),
    ]
